#' @title Uncertainty analysis of IPMs
#'
#' @description Performs uncertainty analysis of IPMs.
#'
#' @param ipm An \code{ipmr} IPM object.
#' @param pars A character vector of parameter names on which to perform the
#'  uncertainty analysis. Defaults to all parameters in \code{ipm}.
#' @param samples A data.frame containing sampled parameter values.
#' @param kernels A character vector specifying the kernel structure in row
#'  major order.
#' @param vr_table A data.frame with columns 'parameter' and 'vital_rate'
#'  mapping each parameter to a user-defined vital rate category. Every
#'  parameter in \code{pars} must be present exactly once in this table.
#' @param delta A numeric scalar specifying the perturbation size used for
#'  numerical differentiation when calculating sensitivities. Default is 1e-4.
#' @param bounds An optional named list specifying lower and/or upper bounds
#'  for model parameters when calculating numerical sensitivities. Each element
#'  should be a numeric vector of length two giving the lower and upper bounds,
#'  respectively (e.g., \code{list(surv = c(0, 1), recruit = c(0, Inf))}).
#'  Parameters omitted from this list are assumed to be unbounded and are
#'  perturbed using the central finite difference. For parameters with
#'  specified bounds, the function automatically uses a forward or backward
#'  finite difference whenever perturbation by \code{delta} would cross a
#'  boundary; otherwise, the central finite difference is used.
#' @param cores An integer specifying the number of cores between which the
#'  computations will be distributed. Defaults to 1.
#'
#'@details
#' Currently implemented for deterministic ("det"), density-independent
#' ("di") IPMs constructed with \code{ipmr}. Stochastic ("stoch") and
#' density-dependent ("dd") IPMs are not supported.
#'
#' Sampled parameter values may either be drawn from the joint distribution or
#' iteratively refit to bootstrapped data. The \code{samples} dataframe must
#' contain columns for all parameters needed to build the IPM, including those
#' which do not vary between samples.
#'
#' Because parameters may appear in multiple kernels or represent multiple
#' biological processes, \code{ipmr} does not attempt to infer vital rate
#' categories automatically. Users must explicitly define this categorization.
#' A template for \code{vr_table} can be generated by calling the function with
#' \code{vr_table = "template"}.
#'
#' The finite-difference scheme used in \code{\link{sensitivity}} is used when
#' estimating parameter sensitivities for the uncertainty decomposition.
#' Consequently, supplying biological parameter bounds ensures that
#' sensitivities are evaluated only within the feasible parameter space
#' throughout the uncertainty analysis. The \code{delta} argument controls the
#' perturbation size used in the sensitivity approximation.
#'
#' On systems with multiple cores, computations can be parallelized using the
#' \code{cores} argument. The function does not automatically infer scheduler
#' resource limits on high-performance computing (HPC) systems.
#'
#' Users running analyses on shared clusters (e.g. via Slurm, PBS, or similar
#' job schedulers) should ensure that the number of cores requested does not
#' exceed the allocation specified by the job submission script. Using all
#' available system cores may lead to oversubscription and reduced performance
#' of concurrent jobs.
#'
#' @return
#' An object of class \code{"ipmr_uncertainty"} containing:
#' \itemize{
#'   \item \code{ipm}: The complete IPM object as specified in \code{ipm}.
#'   \item \code{lambdas}: Population growth rates (\eqn{\lambda}) calculated
#'     for each sampled parameter set.
#'   \item \code{mod_uncert}: The variance in \eqn{\lambda} across all sampled
#'     parameter sets.
#'   \item \code{params_uncert}: A data frame summarizing parameter-level
#'     sensitivities, elasticities, finite-difference methods, sampling
#'     variance, coefficients of variation, and contributions to uncertainty.
#'   \item \code{vr_uncert}: A data frame summarizing variance contributions
#'     aggregated by user-defined vital rate, if given.
#' }
#'
#' @examples
#' # Generate a template for defining vital rates
#' # vr <- uncertainty(ipm, vr_table = "template")
#'
#' # Fill in the vital_rate column manually, then run:
#' # vr$vital_rate <- c("survival", "growth", "reproduction", ...)
#'
#' # Run uncertainty analysis
#' # out <- uncertainty(ipm, pars, samples, kernels, vr_table = vr)
#'
#' @importFrom dplyr bind_rows left_join rename group_by summarize join_by
#' @importFrom stats var sd cov
#' @importFrom reshape2 melt
#'
#' @export
uncertainty <- function(ipm, pars = NULL, samples, kernels, vr_table,
                        delta = 1e-4, bounds = NULL, cores = 1) {

  if (isTRUE(vr_table == "template")) {
    if (is.null(pars)) {
      pars <- names(parameters(ipm))
    }
    return(data.frame(
      parameter = pars,
      vital_rate = NA_character_
    ))
  }


  ## ---- Input checks
  val <- validate_ipm_uncertainty(ipm, pars, samples, kernels,
                                  vr_table, delta, bounds, cores)

  ipm      <- val$ipm
  pars     <- val$pars
  samples  <- val$samples
  kernels  <- val$kernels
  vr_table <- val$vr_table
  delta    <- val$delta
  bounds   <- val$bounds
  cores    <- val$cores

  npar <- length(pars)
  nsam <- nrow(samples)

  ## ---- Parallel setup
  base_ipm <- ipm$proto_ipm
  cluster <- parallel::makePSOCKcluster(cores)
  on.exit(parallel::stopCluster(cluster), add = TRUE)

  parallel::clusterEvalQ(cluster, {
    library(ipmr)
  })

  parallel::clusterExport(
    cluster,
    c("base_ipm", "samples", "pars", "kernels", "delta", "bounds"),
    envir = environment()
  )

  ## ---- Worker
  main_process_opt <- function(i) {

    ipm_temp <- base_ipm
    parameters(ipm_temp) <- samples[i, ]

    ipm_temp <- make_ipm(ipm_temp, iterate = FALSE)

    ker_base <- make_iter_kernel(ipm_temp, mega_mat = kernels)
    mat_base <- ker_base[[1]]

    lambda_base <- Re(eigen(mat_base, only.values = TRUE)$values[1])

    pars_all <- parameters(ipm_temp)

    calc_lambda <- function(par, value) {
      pars_tmp <- pars_all
      pars_tmp[[par]] <- value
      ipm_tmp <- base_ipm
      parameters(ipm_tmp) <- pars_tmp
      ipm_tmp <- make_ipm(ipm_tmp, iterate = FALSE)
      ker <- make_iter_kernel(ipm_tmp,
                              mega_mat = kernels)
      Re(eigen(ker[[1]], only.values = TRUE)$values[1])
    }

    sens <- numeric(length(pars))
    names(sens) <- pars
    diff_method <- character(length(pars))

    ## ---- Sensitivity loop
    for (j in seq_along(pars)) {
      par_now <- pars[j]
      theta   <- pars_all[[par_now]]
      if (!is.null(bounds) &&
          par_now %in% names(bounds)) {
        lower <- bounds[[par_now]][1]
        upper <- bounds[[par_now]][2]
      } else {
        lower <- -Inf
        upper <- Inf
      }
      use_forward  <- theta - delta < lower
      use_backward <- theta + delta > upper
      if (use_forward) {
        lambda_up <- calc_lambda(par_now, theta + delta)
        sens[j] <- (lambda_up - lambda_base) / delta
        diff_method[j] <- "forward"
      } else if (use_backward) {
        lambda_down <- calc_lambda(par_now, theta - delta)
        sens[j] <- (lambda_base - lambda_down) / delta
        diff_method[j] <- "backward"
      } else {
        lambda_down <- calc_lambda(par_now, theta - delta)
        lambda_up <- calc_lambda(par_now, theta + delta)
        sens[j] <- (lambda_up - lambda_down) / (2 * delta)
        diff_method[j] <- "central"
      }
    }

    elas <- sens * abs(as.numeric(pars_all[pars]) / lambda_base)

    list(
      lambda      = data.frame(lambda = lambda_base),
      sens        = as.data.frame(t(sens)),
      elas        = as.data.frame(t(elas)),
      diff_method = as.data.frame(t(diff_method),
                                  stringsAsFactors = FALSE)
    )
  }

  summarize_difference_method <- function(x) {
    tab <- sort(table(x), decreasing = TRUE)
    if (length(tab) == 1) {
      return(names(tab))
    }
    pct <- format( round(100 * tab / sum(tab), 1),trim = TRUE, nsmall = 0 )
    paste0( "mixed (", paste0(pct, "% ", names(tab), collapse = ", "), ")" )
  }

  ## ---- Run parallel
  main <- parallel::parLapply(cluster, seq_len(nsam), main_process_opt)

  ## ---- Combine
  lam_sam  <- dplyr::bind_rows(lapply(main, `[[`, "lambda"))
  sens_sam <- dplyr::bind_rows(lapply(main, `[[`, "sens"))
  elas_sam <- dplyr::bind_rows(lapply(main, `[[`, "elas"))
  diff_sam <- dplyr::bind_rows(lapply(main, `[[`, "diff_method"))

  var_lambda <- stats::var(lam_sam$lambda)

  ## ---- Summary stats
  stats_temp <- data.frame(
    parameter         = pars,
    sensitivity       = colMeans(sens_sam),
    elasticity        = colMeans(elas_sam),
    difference_method = NA,
    variance          = NA,
    se                = NA,
    cv                = NA
  )

  stats_temp$difference_method <- vapply(diff_sam, summarize_difference_method,
                                         character(1))

  par_idx <- match(pars, colnames(samples))

  for (i in seq_len(npar)) {
    dat_temp <- samples[, par_idx[i]]
    stats_temp[i, "variance"] <- stats::var(dat_temp)
    stats_temp[i, "se"] <- stats::sd(dat_temp) / sqrt(length(dat_temp))
    stats_temp[i, "cv"] <- stats::sd(dat_temp) / mean(dat_temp) * 100
  }

  ## ---- Covariance contributions
  cov_temp <- stats::cov(samples[, pars])

  cov_long <- reshape2::melt(cov_temp)
  colnames(cov_long) <- c("par1", "par2", "covariance")

  sens_lookup <- stats_temp[, c("parameter", "sensitivity")]

  cov_long <- cov_long %>%
    dplyr::left_join(
      sens_lookup %>% dplyr::rename(sens1 = sensitivity),
      by = c("par1" = "parameter")
    ) %>%
    dplyr::left_join(
      sens_lookup %>% dplyr::rename(sens2 = sensitivity),
      by = c("par2" = "parameter")
    )

  cov_long$variance_part <- cov_long$covariance * cov_long$sens1 * cov_long$sens2

  var_cont <- cov_long |>
    dplyr::group_by(.data$par1) |>
    dplyr::summarize(variance_sum = sum(.data$variance_part), .groups = "drop")

  var_cont$variance_prop <- var_cont$variance_sum / var_lambda

  stats_temp <- dplyr::left_join(stats_temp, var_cont,
                                 by = c("parameter" = "par1"))

  ## ---- Add vital rates
  stats_temp <- dplyr::left_join(stats_temp, vr_table, by = "parameter")

  ## ---- Add summary by vital rates
  vr_uncert <- stats_temp %>%
    dplyr::group_by(.data$vital_rate) %>%
    dplyr::summarize(
      variance_sum = sum(.data$variance_sum, na.rm = TRUE),
      .groups = "drop"
    )

  ## ---- Return
  new_ipmr_uncertainty(
    ipm           = ipm,
    lambdas       = lam_sam,
    mod_uncert    = var_lambda,
    params_uncert = stats_temp,
    vr_uncert     = vr_uncert
  )
}
