#' @title Uncertainty analysis of IPMs
#'
#' @description Performs uncertainty analysis of IPMs.
#'
#' @param ipm An \code{ipmr} IPM object.
#' @param pars A character vector of parameter names on which to perform the
#'  uncertainty analysis. Defaults to all parameters in \code{ipm}.
#' @param samples A data.frame containing sampled parameter values.
#' @param kernels A character vector specifying the kernel structure in row
#'  major order.
#' @param vr_table A data.frame with columns 'parameter' and 'vital_rate'
#'  mapping each parameter to a user-defined vital rate category. Every
#'  parameter in \code{pars} must be present exactly once in this table.
#' @param delta A numeric scalar specifying the perturbation size used for
#'  numerical differentiation when calculating sensitivities. Default is 1e-4.
#' @param cores An integer specifying the number of cores between which the
#'  computations will be distributed. Defaults to 1.
#'
#'@details
#' Currently implemented for deterministic ("det"), density-independent
#' ("di") IPMs constructed with \code{ipmr}. Stochastic ("stoch") and
#' density-dependent ("dd") IPMs are not supported.
#'
#' Sampled parameter values may either be drawn from the joint distribution or
#' iteratively refit to bootstrapped data. The \code{samples} dataframe must
#' contain columns for all parameters needed to build the IPM, including those
#' which do not vary between samples.
#'
#' Because parameters may appear in multiple kernels or represent multiple
#' biological processes, \code{ipmr} does not attempt to infer vital rate
#' categories automatically. Users must explicitly define this categorization.
#' A template for \code{vr_table} can be generated by calling the function with
#' \code{vr_table = "template"}.
#'
#' Sensitivities within each sampled model are computed using a central
#' difference approximation (see \code{\link{sensitivity}}). The \code{delta}
#' argument controls the perturbation size used in this approximation.
#'
#' On systems with multiple cores, computations can be parallelized using the
#' \code{cores} argument. The function does not automatically infer scheduler
#' resource limits on high-performance computing (HPC) systems.
#'
#' Users running analyses on shared clusters (e.g. via Slurm, PBS, or similar
#' job schedulers) should ensure that the number of cores requested does not
#' exceed the allocation specified by the job submission script. Using all
#' available system cores may lead to oversubscription and reduced performance
#' of concurrent jobs.
#'
#' @return
#'
#' @examples
#' # Generate a template for defining vital rates
#' vr <- uncertainty(ipm, vr_table = "template")
#'
#' # Fill in the vital_rate column manually, then run:
#' # vr$vital_rate <- c("survival", "growth", "reproduction", ...)
#'
#' # Run uncertainty analysis
#' # out <- uncertainty(ipm, pars, samples, kernels, vr_table = vr)
#'
#' @export
uncertainty <- function(ipm, pars = NULL, samples, kernels, vr_table,
                        delta = 1e-4, cores = 1) {

  if (isTRUE(vr_table == "template")) {
    if (is.null(pars)) {
      pars <- names(parameters(ipm))
    }
    return(data.frame(
      parameter = pars,
      vital_rate = NA_character_
    ))
  }

  ## ---- Input checks
  val <- validate_ipm_uncertainty(ipm, pars, samples, kernels,
                                  vr_table, delta, cores)

  ipm      <- val$ipm
  pars     <- val$pars
  samples  <- val$samples
  kernels  <- val$kernels
  vr_table <- val$vr_table
  cores    <- val$cores

  npar <- length(pars)
  nsam <- nrow(samples)

  ## ---- Parallel setup
  base_ipm <- ipm$proto_ipm
  cluster <- parallel::makePSOCKcluster(cores)
  on.exit(parallel::stopCluster(cluster), add = TRUE)

  parallel::clusterEvalQ(cluster, {
    library(ipmr)
  })

  parallel::clusterExport(
    cluster,
    c("base_ipm", "samples", "pars", "kernels", "delta"),
    envir = environment()
  )

  ## ---- Worker
  main_process_opt <- function(i) {

    ipm_temp <- base_ipm
    parameters(ipm_temp) <- samples[i, ]

    ipm_temp <- make_ipm(ipm_temp, iterate = FALSE)

    ker_base <- make_iter_kernel(ipm_temp, mega_mat = kernels)
    mat_base <- ker_base[[1]]

    lambda_base <- Re(eigen(mat_base, only.values = TRUE)$values[1])

    pars_all <- parameters(ipm_temp)

    sens <- numeric(length(pars))
    names(sens) <- pars

    ## ---- Sensitivity loop
    for (j in seq_along(pars)) {

      par_now <- pars[j]

      ## DOWN perturbation
      pars_down <- pars_all
      pars_down[[par_now]] <- pars_down[[par_now]] - delta

      ipm_down <- base_ipm
      parameters(ipm_down) <- pars_down

      ipm_down <- make_ipm(ipm_down, iterate = FALSE)
      ker_down <- make_iter_kernel(ipm_down, mega_mat = kernels)

      lambda_down <- Re(eigen(ker_down[[1]], only.values = TRUE)$values[1])

      ## UP perturbation
      pars_up <- pars_all
      pars_up[[par_now]] <- pars_up[[par_now]] + delta

      ipm_up <- base_ipm
      parameters(ipm_up) <- pars_up

      ipm_up <- make_ipm(ipm_up, iterate = FALSE)
      ker_up <- make_iter_kernel(ipm_up, mega_mat = kernels)

      lambda_up <- Re(eigen(ker_up[[1]], only.values = TRUE)$values[1])

      sens[j] <- (lambda_up - lambda_down) / (2 * delta)
    }

    elas <- sens * abs(as.numeric(pars_all[pars]) / lambda_base)

    list(
      lambda = data.frame(lambda = lambda_base),
      sens   = as.data.frame(t(sens)),
      elas   = as.data.frame(t(elas))
    )
  }

  ## ---- Run parallel
  main <- parallel::parLapply(cluster, seq_len(nsam), main_process_opt)

  ## ---- Combine
  lam_sam  <- dplyr::bind_rows(lapply(main, `[[`, "lambda"))
  sens_sam <- dplyr::bind_rows(lapply(main, `[[`, "sens"))
  elas_sam <- dplyr::bind_rows(lapply(main, `[[`, "elas"))

  var_lambda <- var(lam_sam$lambda)

  ## ---- Summary stats
  stats_temp <- data.frame(
    parameter   = pars,
    sensitivity = colMeans(sens_sam),
    elasticity  = colMeans(elas_sam),
    variance    = NA,
    se          = NA,
    cv          = NA
  )

  par_idx <- match(pars, colnames(samples))

  for (i in seq_len(npar)) {
    dat_temp <- samples[, par_idx[i]]
    stats_temp[i, "variance"] <- var(dat_temp)
    stats_temp[i, "se"] <- sd(dat_temp) / sqrt(length(dat_temp))
    stats_temp[i, "cv"] <- sd(dat_temp) / mean(dat_temp) * 100
  }

  ## ---- Covariance contributions
  cov_temp <- cov(samples[, pars])

  cov_long <- reshape2::melt(cov_temp)
  colnames(cov_long) <- c("par1", "par2", "covariance")

  sens_lookup <- stats_temp[, c("parameter", "sensitivity")]

  cov_long <- cov_long %>%
    left_join(
      sens_lookup %>% rename(sens1 = sensitivity),
      by = c("par1" = "parameter")
    ) %>%
    left_join(
      sens_lookup %>% rename(sens2 = sensitivity),
      by = c("par2" = "parameter")
    )

  cov_long$variance_part <- cov_long$covariance * cov_long$sens1 * cov_long$sens2

  var_cont <- cov_long |>
    dplyr::group_by(par1) |>
    dplyr::summarize(variance_sum = sum(variance_part), .groups = "drop")

  var_cont$variance_prop <- var_cont$variance_sum / var_lambda

  stats_temp <- dplyr::left_join(stats_temp, var_cont,
                                 by = dplyr::join_by(parameter == par1))

  ## ---- Add vital rates
  stats_temp <- dplyr::left_join(stats_temp, vr_table, by = "parameter")

  ## ---- Add summary by vital rates
  vr_uncert <- stats_temp %>%
    dplyr::group_by(vital_rate) %>%
    dplyr::summarise(
      variance_sum = sum(variance_sum, na.rm = TRUE),
      .groups = "drop"
    )

  ## ---- Return
  new_ipmr_uncertainty(
    ipm           = ipm,
    lambdas       = lam_sam,
    mod_uncert    = var_lambda,
    params_uncert = stats_temp,
    vr_uncert     = vr_uncert
  )
}
